"use client";

import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

export type Language = "id" | "en";

export const DICTIONARY: Record<Language, Record<string, string>> = {
  id: {
    // ── Nav & Common Shell ──
    nav_home: "Beranda",
    nav_history: "Riwayat",
    nav_leave: "Izin & Cuti",
    nav_profile: "Profil",
    logout: "Keluar",
    menu: "Menu",
    notifications: "Notifikasi",
    my_notifications: "Notifikasi Saya",
    refresh: "Segarkan",
    refreshing: "Menyegarkan...",
    mark_read: "Tandai Dibaca",
    no_notifications: "Tidak Ada Notifikasi",
    no_user_notif_desc: "Belum ada pembaruan aktivitas untuk Anda.",
    no_admin_notif_desc: "Belum ada aktivitas notifikasi terbaru.",
    action_needed: "Perlu Aksi",
    activities: "Aktivitas",
    tab_all: "Semua",
    tab_warning: "Peringatan",
    tab_leave: "Izin & Cuti",
    tab_attendance: "Absensi",
    tab_reminder: "Pengingat",
    see_details: "Lihat Detail →",
    open_page: "Buka Halaman →",
    cancel: "Batal",
    save: "Simpan",
    saving: "Menyimpan…",
    search: "Cari...",
    ok: "Oke",
    delete: "Hapus",
    edit: "Edit",
    status: "Status",
    date: "Tanggal",
    time: "Waktu",
    notes: "Catatan",
    actions: "Aksi",

    // ── Login ──
    login_title: "Bee Absensi",
    login_subtitle: "Masuk untuk melanjutkan ke akun Anda.",
    email_address: "Alamat email",
    email_placeholder: "nama@perusahaan.com",
    password: "Kata sandi",
    login_password_placeholder: "Masukkan kata sandi",
    show: "Tampil",
    hide: "Sembunyi",
    remember_me: "Ingat saya",
    login_button: "Masuk",
    login_footer_note: "Gunakan akun yang telah didaftarkan oleh admin.",
    login_footer_sec: "Akses Anda terlindungi dengan autentikasi token.",
    network_error: "Tidak dapat terhubung ke server. Coba lagi.",

    // ── Attendance Dashboard (Beranda) ──
    taking_gps: "Mengambil lokasi GPS...",
    checking_location: "Memeriksa Lokasi...",
    fetching_coords: "Sedang mengambil koordinat GPS...",
    inside_office: "Di Dalam Radius Kantor",
    outside_office: "Di Luar Radius Kantor",
    gps_inactive: "GPS Tidak Aktif",
    gps_denied: "Izin lokasi ditolak. Aktifkan izin lokasi di browser.",
    gps_unavailable: "Lokasi belum tersedia. Periksa GPS Anda.",
    gps_timeout: "Pengambilan lokasi terlalu lama. Coba lagi.",
    browser_no_gps: "Browser tidak mendukung fitur geolokasi GPS.",
    gps_not_detected: "Lokasi GPS tidak terdeteksi. Aktifkan GPS Anda.",
    can_clock_in_now: "Anda berada dalam radius kantor, silakan melakukan absensi.",
    must_be_in_radius: "Anda berada di luar radius kantor untuk clock in.",
    clock_in_btn: "CLOCK IN",
    clock_out_btn: "CLOCK OUT",
    clock_completed_btn: "SUDAH SELESAI",
    hint_clock_in: "Pastikan Anda berada di dalam area kantor untuk clock in.",
    hint_clock_out: "Pastikan Anda telah menyelesaikan pekerjaan hari ini.",
    hint_completed: "Anda sudah menyelesaikan absensi masuk dan pulang untuk hari ini.",
    clock_in_title: "Jam Masuk",
    clock_out_title: "Jam Pulang",
    work_duration: "Total Jam Kerja",
    not_clocked_in: "Belum Absen",
    not_clocked_out: "Belum Pulang",
    status_on_time: "Tepat Waktu",
    status_late: "Terlambat",
    status_absent: "Tidak Hadir",
    wib: "WIB",
    map_placeholder: "Memuat peta lokasi...",
    no_location: "Lokasi Belum Terdeteksi",
    in_office_radius: "Di dalam radius kantor",
    allow_location_access: "Aktifkan GPS & izinkan akses lokasi di browser",
    enable_btn: "Aktifkan",
    hours_summary_title: "Jam Kerja Hari Ini",
    secure_card_title: "KEAMANAN",
    feature_anti_fake_gps: "Anti-Fake GPS Aktif",
    feature_liveness: "Verifikasi Wajah Aktif",
    feature_encrypted: "Data Terenkripsi",
    unit_hours: "jam",
    unit_mins: "menit",
    attendance_failed: "Gagal melakukan absensi.",

    // Camera Capture Modal
    camera_title: "Verifikasi Foto Wajah",
    camera_snap: "Ambil Foto",
    camera_retake: "Foto Ulang",
    camera_confirm: "Gunakan Foto Ini",
    camera_loading: "Menyiapkan kamera...",
    camera_denied: "Izin kamera ditolak. Berikan izin di browser Anda.",

    // ── Attendance History (Riwayat) ──
    history_title: "Riwayat Kehadiran",
    history_subtitle: "Rekap absensi Anda per bulan.",
    total_present: "Total Hadir",
    total_late: "Terlambat",
    total_absent: "Tidak Hadir",
    filter_all: "Semua",
    filter_on_time: "Tepat Waktu",
    filter_late: "Terlambat",
    filter_absent: "Tidak Hadir",
    no_history_data: "Tidak ada data untuk",
    no_history_hint: "Coba pilih bulan lain atau hapus filter status.",
    entry_in: "Masuk",
    entry_out: "Pulang",
    duration_label: "Durasi",
    load_more: "Muat lebih banyak",
    loading_more: "Memuat…",
    remaining: "lagi",
    all_data_shown: "Semua data telah ditampilkan.",
    prev_month: "Bulan sebelumnya",
    next_month: "Bulan berikutnya",
    history_load_failed: "Gagal memuat riwayat kehadiran.",

    // ── Leave Request Page (Izin & Cuti) ──
    leave_page_title: "Pengajuan Izin / Cuti",
    leave_page_subtitle: "Ajukan izin, cuti, atau sakit kepada admin.",
    tab_request_form: "Formulir Pengajuan",
    tab_request_history: "Riwayat Pengajuan",
    leave_type: "Jenis Pengajuan",
    select_leave_type: "Pilih jenis pengajuan...",
    type_sick: "Izin Sakit",
    type_leave: "Cuti Tahunan",
    type_permission: "Izin Keperluan Pribadi",
    date_range: "Rentang Tanggal",
    date_start: "MULAI",
    date_end: "SELESAI",
    reason: "Alasan",
    reason_placeholder: "Jelaskan alasan pengajuan Anda (min. 10 karakter)...",
    supporting_doc: "Dokumen Pendukung (opsional)",
    supporting_doc_hint: "Mis. Surat Keterangan Dokter",
    tap_to_upload: "Ketuk untuk upload file",
    upload_specs: "PDF, JPG, PNG hingga 5 MB",
    submit_request: "Kirim Pengajuan",
    submitting_request: "Mengirim...",
    status_pending: "Menunggu Persetujuan",
    status_approved: "Disetujui",
    status_rejected: "Ditolak",
    no_leave_history: "Belum ada riwayat pengajuan izin atau cuti.",
    no_leave_history_desc: "Pengajuan yang Anda kirimkan akan tercatat dan ditampilkan di sini.",
    confirm_cancel_leave: "Batalkan pengajuan ini?",
    leave_submitted_success: "Pengajuan berhasil dikirim dan menunggu persetujuan.",
    cancel_leave_failed: "Gagal membatalkan pengajuan.",
    select_date_range: "Pilih rentang tanggal.",
    invalid_date_range: "Tanggal selesai harus setelah atau sama dengan tanggal mulai.",
    reason_min_length: "Alasan minimal 10 karakter.",
    leave_load_failed: "Gagal memuat daftar pengajuan.",

    // ── Profile Page ──
    profile_title: "Profil & Pengaturan",
    summary_this_month: "Ringkasan Bulan Ini",
    leave_remaining: "Sisa Cuti",
    present: "Hadir",
    late: "Terlambat",
    sick_leave: "Sakit / Izin",
    unit_days: "Hari",
    unit_times: "Kali",
    personal_info: "Informasi Personal",
    email: "Email",
    phone_wa: "WhatsApp / Telepon",
    emergency_contact: "Kontak Darurat",
    not_filled: "Belum diisi",
    department: "Departemen",
    position: "Jabatan",
    edit_contact_title: "Edit Profil",
    edit_profile_desc: "Perbarui foto profil, nama, dan data kontak Anda",
    profile_photo: "Foto Profil",
    change_photo: "Ubah Foto",
    upload_photo: "Pilih Foto",
    remove_photo: "Hapus Foto",
    photo_hint: "Maksimal 5MB (JPG, PNG, WebP)",
    full_name: "Nama Lengkap",
    full_name_placeholder: "Nama lengkap",
    nip_nim: "NIP / NIM",
    nip_nim_placeholder: "Nomor Induk Pegawai / Mahasiswa",
    save_changes: "Simpan Perubahan",
    profile_updated_toast: "Profil berhasil diperbarui!",
    security_account: "Keamanan & Akun",
    change_password: "Ubah Kata Sandi",
    change_password_desc: "Ganti kata sandi akun Anda",
    current_password: "Kata Sandi Saat Ini",
    current_password_placeholder: "Kata sandi lama",
    new_password: "Kata Sandi Baru",
    new_password_placeholder: "Min. 8 karakter",
    confirm_password: "Konfirmasi Kata Sandi Baru",
    confirm_password_placeholder: "Ulangi kata sandi baru",
    password_changed_success: "Kata sandi berhasil diubah!",
    password_changed_desc: "Semua sesi aktif telah diakhiri. Silakan masuk kembali.",
    app_settings: "Pengaturan Aplikasi",
    notif_active: "Aktif (Menerima pemberitahuan)",
    notif_inactive: "Nonaktif",
    choose_language: "Pilih Bahasa",
    language_display_desc: "Bahasa tampilan aplikasi",
    language_modal_title: "Pilih Bahasa Aplikasi",
    language_modal_subtitle: "Pilih bahasa tampilan yang Anda inginkan",
    lang_id_name: "Bahasa Indonesia",
    lang_id_desc: "Bahasa resmi aplikasi",
    lang_en_name: "English",
    lang_en_desc: "Bahasa internasional",
    notif_enabled_toast: "Notifikasi aplikasi berhasil diaktifkan",
    notif_disabled_toast: "Notifikasi aplikasi dinonaktifkan",
    lang_changed_toast: "Bahasa diubah ke Bahasa Indonesia",

    // ── Admin Panel Navigation & Shell ──
    admin_nav_dashboard: "Dashboard",
    admin_nav_attendance: "Absensi",
    admin_nav_leave: "Pengajuan Izin",
    admin_nav_employees: "Karyawan",
    admin_nav_reports: "Laporan",
    admin_nav_settings: "Settings",
    admin_nav_support: "Support",
    admin_panel_badge: "Admin Panel",
    dashboard_overview: "Dashboard Overview",
    admin_role_title: "System Administrator",

    // ── Admin Dashboard ──
    admin_greeting: "Selamat datang",
    attendance_rate: "Persentase Kehadiran",
    today_badge: "Hari Ini",
    last_7_days: "Kehadiran 7 Hari Terakhir",
    last_7_days_desc: "Tren tingkat kehadiran karyawan mingguan",
    recent_leave: "Pengajuan Izin Terbaru",
    awaiting_confirmation: "Menunggu Konfirmasi",
    approved_this_month: "Disetujui Bulan Ini",
    need_review: "Perlu Tinjauan",
    no_recent_leave: "Tidak ada pengajuan izin terbaru.",
    admin_export_report: "Export Laporan",
    admin_total_present: "TOTAL HADIR",
    admin_on_time: "TEPAT WAKTU",
    admin_late: "TERLAMBAT",
    admin_absent: "BELUM ABSEN",
    admin_attendance_percentage: "Persentase Kehadiran",
    admin_today: "Hari Ini",
    admin_attendance_rate: "Tingkat Hadir",
    admin_leave_requests: "Pengajuan Izin",
    admin_pending_approval: "Menunggu Persetujuan",
    admin_approved_this_month: "Disetujui Bulan Ini",
    admin_attendance_last_7_days: "Kehadiran 7 Hari Terakhir",
    admin_trend_weekly: "Tren tingkat kehadiran karyawan mingguan",
    admin_view_details: "Lihat Detail",
    admin_dashboard_error: "Gagal memuat data dashboard.",

    // ── Admin Attendance Monitoring ──
    admin_attendance_title: "Monitoring Absensi",
    admin_attendance_subtitle: "Pantau kehadiran seluruh karyawan dan bukti foto selfie",
    admin_attendance_desc: "Pantau status dan log absensi seluruh karyawan secara realtime.",
    total_staff: "Total Karyawan",
    export_data: "Ekspor Data",
    filter_date: "Pilih Tanggal",
    filter_dept: "Semua Departemen",
    filter_status: "Semua Status",
    showing_label: "Menampilkan",
    data_count: "data",
    no_attendance_data: "Tidak ada data absensi",
    no_attendance_data_desc: "Belum ada karyawan yang absen pada tanggal ini",
    th_employee: "Karyawan",
    th_department: "Departemen",
    th_clock_in: "Jam Masuk",
    th_clock_out: "Jam Pulang",
    th_photo_proof: "Foto Bukti",
    th_status: "Status",
    photo_modal_title: "Foto Bukti Absen",
    attendance_time: "Waktu Absensi",
    dept_position: "Departemen / Jabatan",
    gps_coordinates: "Koordinat GPS",
    photo_in: "Foto Masuk",
    photo_out: "Foto Pulang",
    close: "Tutup",
    prev: "Prev",
    next: "Next",
    page_prefix: "Halaman",
    page_of: "dari",
    attendance_load_failed: "Gagal memuat data absensi.",

    // ── Admin Leave Management ──
    admin_leave_title: "Pengajuan Izin & Cuti",
    admin_leave_subtitle: "Kelola dan proses pengajuan dari karyawan",
    admin_leave_desc: "Tinjau, setujui, atau tolak permohonan izin dan cuti dari karyawan.",
    type_sick_short: "Sakit",
    type_leave_short: "Cuti",
    type_permission_short: "Izin",
    no_leave_requests: "Tidak ada pengajuan",
    no_leave_requests_desc: "Belum ada pengajuan dengan filter ini",
    days_count: "hari",
    rejected_prefix: "Ditolak",
    processed_by: "Diproses",
    detail_btn: "Detail",
    approve_btn: "Setujui",
    reject_btn: "Tolak",
    reject_modal_title: "Tolak Pengajuan",
    reject_modal_from: "dari",
    reject_reason_label: "Alasan penolakan",
    optional: "(opsional)",
    reject_reason_placeholder: "Tulis alasan penolakan…",
    processing: "Memproses…",
    leave_detail_title: "Detail Pengajuan",
    view_document: "Lihat dokumen →",
    attachment: "Lampiran",
    approval_modal_title: "Konfirmasi Persetujuan",
    rejection_modal_title: "Konfirmasi Penolakan",
    leave_load_failed_admin: "Gagal memuat data pengajuan.",
    approve_failed: "Gagal menyetujui.",
    reject_failed: "Gagal menolak.",

    // ── Admin Employee Management ──
    admin_emp_title: "Daftar Karyawan",
    emp_registered: "karyawan terdaftar",
    emp_all_registered: "Seluruh karyawan yang terdaftar di sistem",
    add_employee: "Tambah Karyawan",
    search_name_nip: "Cari nama atau NIP…",
    all_departments: "Semua Departemen",
    emp_not_found: "Karyawan tidak ditemukan",
    emp_not_found_desc: "Coba ubah kata kunci atau tambah karyawan baru",
    active: "Aktif",
    inactive: "Nonaktif",
    activate: "Aktifkan",
    deactivate: "Nonaktifkan",
    leave_quota_label: "Cuti",
    edit_employee_title: "Edit Karyawan",
    create_employee_desc: "Isi data untuk membuat akun karyawan baru",
    edit_employee_desc: "Edit data karyawan",
    account_data: "Data Akun",
    new_password_optional: "Password Baru (opsional)",
    edit_password_placeholder: "Kosongkan jika tidak diubah",
    password_placeholder: "Min. 6 karakter",
    account_status: "Status Akun",
    account_status_hint: "Karyawan bisa login jika aktif",
    profile_data: "Data Profil",
    phone_number: "No. Telepon",
    quota_hint: "Kuota Cuti (hari/tahun)",
    create_employee_btn: "Buat Karyawan",
    delete_employee_title: "Hapus Karyawan",
    delete_employee_confirm: "akan dihapus dari sistem.",
    delete_warning: "Data yang dihapus tidak dapat dikembalikan.",
    emp_load_failed: "Gagal memuat data karyawan.",
    emp_create_failed: "Gagal membuat karyawan.",
    emp_update_failed: "Gagal memperbarui karyawan.",
    emp_delete_failed: "Gagal menghapus karyawan.",

    // ── Admin Report ──
    report_page_title: "Laporan & Export Absensi",
    report_page_subtitle: "Rekap dan unduh spreadsheet absensi tahunan, bulanan, mingguan, maupun harian.",
    export_spreadsheet: "Export Spreadsheet (Excel / CSV)",
    exporting_spreadsheet: "Membuat Spreadsheet…",
    period_yearly: "Tahunan",
    period_monthly: "Bulanan",
    period_weekly: "Mingguan",
    period_daily: "Harian",
    period_custom: "Rentang Kustom",
    select_year: "Pilih Tahun:",
    month_and_year: "Bulan & Tahun:",
    select_date: "Pilih Tanggal:",
    from_date: "Dari:",
    to_date: "Sampai:",
    this_week: "Minggu Ini",
    report_load_failed: "Gagal memuat laporan absensi.",
    export_download_failed: "Gagal mengunduh laporan spreadsheet.",
    search_report_placeholder: "Cari nama atau NIP karyawan…",
    search_btn: "Cari",
    preview_data: "Preview Data",
    show_per_page: "Tampilkan:",
    rows_unit: "baris",
    no_report_data: "Tidak ada data absensi",
    no_report_data_desc: "Tidak ada data untuk filter periode yang dipilih.",
    total_attendance_stat: "Total Kehadiran",
    recorded_attendance: "Data absensi tercatat",
    of_total: "dari total",
    need_action: "Perlu tindak lanjut",
    th_duration: "Durasi",
    th_date: "Tanggal",
    th_in: "Masuk",
    th_out: "Pulang",
    btn_in: "Masuk",
    btn_out: "Pulang",
    photo_proof_in: "Foto Bukti Absen Masuk",
    photo_proof_out: "Foto Bukti Absen Pulang",
    photo_not_available: "Foto Tidak Tersedia",

    // ── Admin Settings ──
    settings_title: "Pengaturan Sistem",
    settings_subtitle: "Kelola konfigurasi aplikasi, aturan absensi, notifikasi, dan profil akun administrator",
    settings_saved: "Pengaturan berhasil disimpan!",
    tab_general: "Umum",
    tab_attendance_rules: "Absensi",
    tab_notification_settings: "Notifikasi",
    tab_admin_account: "Akun",
    general_settings: "Pengaturan Umum",
    general_settings_desc: "Informasi dasar aplikasi dan perusahaan",
    app_name: "Nama Aplikasi",
    company_name: "Nama Perusahaan",
    timezone: "Zona Waktu",
    language: "Bahasa",
    save_settings: "Simpan Pengaturan",
    saving_settings: "Menyimpan…",
    schedule_mode_title: "Mode Jam Kerja",
    schedule_same_title: "Semua Hari Sama",
    schedule_same_desc: "Satu jam masuk & jam pulang yang sama untuk semua hari kerja.",
    schedule_custom_title: "Beda Jam Tiap Hari (Kustom)",
    schedule_custom_desc: "Atur jam masuk & jam pulang berbeda untuk tiap hari (misal: Jumat beda jam).",
    uniform_schedule: "Jam Kerja Seragam",
    clock_in_time_label: "Jam Masuk Kerja",
    clock_out_time_label: "Jam Pulang Kerja",
    active_work_days: "Hari Kerja Aktif",
    custom_schedule_active: "Jadwal Jam Kerja Kustom Aktif",
    custom_schedule_active_desc: "Tiap hari memiliki jam masuk dan jam pulang tersendiri.",
    preset_fri_btn: "Set Senin–Kamis 08:30 & Jumat 10:00",
    preset_copy_mon_btn: "Salin Jam Senin ke Sel-Kam",
    day_active_status: "Hari Kerja Aktif",
    day_off_status: "Libur",
    special_badge: "Khusus",
    no_attendance_required_day: "Karyawan tidak diwajibkan absensi pada hari ini",
    rules_section_title: "Aturan Keterlambatan & Batas Check-in",
    rules_section_desc: "Aturan kelonggaran telat dan batas akhir check-in (berlaku untuk semua mode jam kerja).",
    late_tolerance_title: "Toleransi Keterlambatan",
    late_tolerance_desc: "Kelonggaran waktu setelah jam masuk sebelum kehadiran dihitung terlambat.",
    cutoff_title: "Batas Akhir Check-in",
    cutoff_desc: "Batas waktu toleransi maksimal sebelum sistem menolak absen masuk.",
    custom_minutes_option: "✏️ Kustom / Isi Menit Sendiri...",
    no_cutoff_option: "0 / Tanpa Batas Akhir (Bebas Kapan Saja)",
    unit_minutes: "Menit",
    select_btn: "Pilih",
    office_radius_title: "Lokasi & Radius",
    office_radius_label: "Radius Check-in (meter)",
    office_radius_desc: "Karyawan harus berada dalam radius ini dari kantor untuk bisa check-in",
    notif_settings_title: "Pengaturan Notifikasi",
    notif_settings_desc: "Pilih notifikasi yang ingin Anda terima",
    grp_email_attendance: "Email — Kehadiran",
    notif_late_emp: "Karyawan Terlambat",
    notif_late_emp_desc: "Kirim email saat karyawan check-in setelah batas waktu",
    notif_absent_emp: "Karyawan Belum Absen",
    notif_absent_emp_desc: "Kirim email harian daftar karyawan yang belum check-in",
    grp_email_leave: "Email — Pengajuan Izin",
    notif_new_leave: "Pengajuan Izin Baru",
    notif_new_leave_desc: "Kirim email saat ada karyawan mengajukan izin/cuti",
    notif_leave_status: "Izin Disetujui/Ditolak",
    notif_leave_status_desc: "Kirim email konfirmasi ke karyawan setelah diproses",
    grp_email_reports: "Email — Laporan Otomatis",
    notif_weekly_rep: "Laporan Mingguan",
    notif_weekly_rep_desc: "Kirim ringkasan kehadiran setiap Senin pagi",
    notif_monthly_rep: "Laporan Bulanan",
    notif_monthly_rep_desc: "Kirim rekap bulanan setiap tanggal 1",
    grp_system_log: "Log Sistem",
    notif_admin_login: "Login Admin",
    notif_admin_login_desc: "Catat setiap aktivitas login ke panel admin",
    notif_data_export: "Export Data",
    notif_data_export_desc: "Catat setiap kali data di-export",
    admin_account_title: "Profil Akun",
    admin_account_desc: "Kelola informasi akun administrator",
    admin_save_profile: "Simpan Profil",
    admin_change_pw_title: "Ubah Password",
    admin_current_pw: "Password Saat Ini",
    admin_new_pw: "Password Baru",
    admin_confirm_pw: "Konfirmasi Password Baru",
    admin_btn_change_pw: "Ganti Password",
    admin_pw_min_error: "Password baru minimal 8 karakter.",
    admin_pw_match_error: "Konfirmasi password tidak cocok.",
    admin_pw_curr_error: "Masukkan password saat ini.",
  },

  en: {
    // ── Nav & Common Shell ──
    nav_home: "Home",
    nav_history: "History",
    nav_leave: "Leave & Request",
    nav_profile: "Profile",
    logout: "Sign Out",
    menu: "Menu",
    notifications: "Notifications",
    my_notifications: "My Notifications",
    refresh: "Refresh",
    refreshing: "Refreshing...",
    mark_read: "Mark as Read",
    no_notifications: "No Notifications",
    no_user_notif_desc: "No recent activity updates for you.",
    no_admin_notif_desc: "No recent activity notifications.",
    action_needed: "Action Needed",
    activities: "Activities",
    tab_all: "All",
    tab_warning: "Warnings",
    tab_leave: "Leave & Permission",
    tab_attendance: "Attendance",
    tab_reminder: "Reminders",
    see_details: "View Details →",
    open_page: "Open Page →",
    cancel: "Cancel",
    save: "Save",
    saving: "Saving…",
    search: "Search...",
    ok: "OK",
    delete: "Delete",
    edit: "Edit",
    status: "Status",
    date: "Date",
    time: "Time",
    notes: "Notes",
    actions: "Actions",

    // ── Login ──
    login_title: "Bee Absensi",
    login_subtitle: "Sign in to continue to your account.",
    email_address: "Email address",
    email_placeholder: "name@company.com",
    password: "Password",
    login_password_placeholder: "Enter password",
    show: "Show",
    hide: "Hide",
    remember_me: "Remember me",
    login_button: "Sign In",
    login_footer_note: "Use an account that has been registered by admin.",
    login_footer_sec: "Your access is protected with token authentication.",
    network_error: "Unable to connect to server. Please try again.",

    // ── Attendance Dashboard (Home) ──
    taking_gps: "Acquiring GPS location...",
    checking_location: "Checking Location...",
    fetching_coords: "Fetching GPS coordinates...",
    inside_office: "Inside Office Radius",
    outside_office: "Outside Office Radius",
    gps_inactive: "GPS Inactive",
    gps_denied: "Location permission denied. Please enable location in your browser.",
    gps_unavailable: "Location unavailable. Please check your GPS signal.",
    gps_timeout: "Acquiring location took too long. Please try again.",
    browser_no_gps: "Browser does not support GPS geolocation.",
    gps_not_detected: "GPS location not detected. Please enable your GPS.",
    can_clock_in_now: "You are within office radius. You can clock in now.",
    must_be_in_radius: "You must be within office radius to clock in.",
    clock_in_btn: "CLOCK IN",
    clock_out_btn: "CLOCK OUT",
    clock_completed_btn: "COMPLETED",
    hint_clock_in: "Ensure you are within the office area to clock in.",
    hint_clock_out: "Ensure you have completed all your work for today.",
    hint_completed: "You have completed your check-in and check-out for today.",
    clock_in_title: "Clock In",
    clock_out_title: "Clock Out",
    work_duration: "Work Duration",
    not_clocked_in: "Not Clocked In",
    not_clocked_out: "Not Clocked Out",
    status_on_time: "On Time",
    status_late: "Late",
    status_absent: "Absent",
    wib: "WIB",
    map_placeholder: "Loading location map...",
    no_location: "Location Not Detected",
    in_office_radius: "Within office radius",
    allow_location_access: "Enable GPS & allow location access in browser",
    enable_btn: "Enable",
    hours_summary_title: "Today's Work Hours",
    secure_card_title: "SECURE",
    feature_anti_fake_gps: "Anti-Fake GPS Active",
    feature_liveness: "Liveness Verified",
    feature_encrypted: "Encrypted Data",
    unit_hours: "hrs",
    unit_mins: "mins",
    attendance_failed: "Failed to submit attendance.",

    // Camera Capture Modal
    camera_title: "Face Photo Verification",
    camera_snap: "Take Photo",
    camera_retake: "Retake",
    camera_confirm: "Use This Photo",
    camera_loading: "Starting camera...",
    camera_denied: "Camera permission denied. Please allow camera access in your browser.",

    // ── Attendance History ──
    history_title: "Attendance History",
    history_subtitle: "Your monthly attendance summary.",
    total_present: "Total Present",
    total_late: "Late",
    total_absent: "Absent",
    filter_all: "All",
    filter_on_time: "On Time",
    filter_late: "Late",
    filter_absent: "Absent",
    no_history_data: "No data for",
    no_history_hint: "Try selecting another month or clearing status filters.",
    entry_in: "In",
    entry_out: "Out",
    duration_label: "Duration",
    load_more: "Load more",
    loading_more: "Loading…",
    remaining: "more",
    all_data_shown: "All records have been displayed.",
    prev_month: "Previous month",
    next_month: "Next month",
    history_load_failed: "Failed to load attendance history.",

    // ── Leave Request Page ──
    leave_page_title: "Leave & Request",
    leave_page_subtitle: "Submit leave, sick, or personal permission to admin.",
    tab_request_form: "Request Form",
    tab_request_history: "Request History",
    leave_type: "Request Type",
    select_leave_type: "Select request type...",
    type_sick: "Sick Leave",
    type_leave: "Annual Leave",
    type_permission: "Personal Permission",
    date_range: "Date Range",
    date_start: "START",
    date_end: "END",
    reason: "Reason",
    reason_placeholder: "Explain the reason for your request (min. 10 characters)...",
    supporting_doc: "Supporting Document (optional)",
    supporting_doc_hint: "E.g. Doctor's Note / Medical Certificate",
    tap_to_upload: "Tap to upload file",
    upload_specs: "PDF, JPG, PNG up to 5 MB",
    submit_request: "Submit Request",
    submitting_request: "Submitting...",
    status_pending: "Pending",
    status_approved: "Approved",
    status_rejected: "Rejected",
    no_leave_history: "No leave or permission request history yet.",
    no_leave_history_desc: "Submitted requests will be recorded and displayed here.",
    confirm_cancel_leave: "Cancel this request?",
    leave_submitted_success: "Request submitted successfully and awaiting approval.",
    cancel_leave_failed: "Failed to cancel request.",
    select_date_range: "Select date range.",
    invalid_date_range: "End date must be on or after start date.",
    reason_min_length: "Reason must be at least 10 characters.",
    leave_load_failed: "Failed to load leave requests.",

    // ── Profile Page ──
    profile_title: "Profile & Settings",
    summary_this_month: "This Month's Summary",
    leave_remaining: "Remaining Leave",
    present: "Present",
    late: "Late",
    sick_leave: "Sick / Leave",
    unit_days: "Days",
    unit_times: "Times",
    personal_info: "Personal Information",
    email: "Email",
    phone_wa: "WhatsApp / Phone",
    emergency_contact: "Emergency Contact",
    not_filled: "Not filled",
    department: "Department",
    position: "Position",
    edit_contact_title: "Edit Profile",
    edit_profile_desc: "Update your profile picture, name, and contact details",
    profile_photo: "Profile Picture",
    change_photo: "Change Photo",
    upload_photo: "Choose Photo",
    remove_photo: "Remove Photo",
    photo_hint: "Max 5MB (JPG, PNG, WebP)",
    full_name: "Full Name",
    full_name_placeholder: "Full name",
    nip_nim: "NIP / NIM",
    nip_nim_placeholder: "Employee or Student ID",
    save_changes: "Save Changes",
    profile_updated_toast: "Profile updated successfully!",
    security_account: "Security & Account",
    change_password: "Change Password",
    change_password_desc: "Update your account password",
    current_password: "Current Password",
    current_password_placeholder: "Old password",
    new_password: "New Password",
    new_password_placeholder: "Min. 8 characters",
    confirm_password: "Confirm New Password",
    confirm_password_placeholder: "Repeat new password",
    password_changed_success: "Password successfully changed!",
    password_changed_desc: "All active sessions have been terminated. Please sign in again.",
    app_settings: "App Settings",
    notif_active: "Active (Receiving notifications)",
    notif_inactive: "Disabled",
    choose_language: "Select Language",
    language_display_desc: "App display language",
    language_modal_title: "Select App Language",
    language_modal_subtitle: "Choose your preferred display language",
    lang_id_name: "Bahasa Indonesia",
    lang_id_desc: "Indonesian official language",
    lang_en_name: "English",
    lang_en_desc: "International English language",
    notif_enabled_toast: "App notifications enabled",
    notif_disabled_toast: "App notifications disabled",
    lang_changed_toast: "Language changed to English",

    // ── Admin Panel Navigation & Shell ──
    admin_nav_dashboard: "Dashboard",
    admin_nav_attendance: "Attendance",
    admin_nav_leave: "Leave Requests",
    admin_nav_employees: "Employees",
    admin_nav_reports: "Reports",
    admin_nav_settings: "Settings",
    admin_nav_support: "Support",
    admin_panel_badge: "Admin Panel",
    dashboard_overview: "Dashboard Overview",
    admin_role_title: "System Administrator",

    // ── Admin Dashboard ──
    admin_greeting: "Welcome",
    attendance_rate: "Attendance Rate",
    today_badge: "Today",
    last_7_days: "Last 7 Days Attendance",
    last_7_days_desc: "Weekly employee attendance trends",
    recent_leave: "Recent Leave Requests",
    awaiting_confirmation: "Awaiting Confirmation",
    approved_this_month: "Approved This Month",
    need_review: "Needs Review",
    no_recent_leave: "No recent leave requests.",
    admin_export_report: "Export Report",
    admin_total_present: "TOTAL PRESENT",
    admin_on_time: "ON TIME",
    admin_late: "LATE",
    admin_absent: "NOT CLOCKED IN",
    admin_attendance_percentage: "Attendance Rate",
    admin_today: "Today",
    admin_attendance_rate: "Attendance Rate",
    admin_leave_requests: "Leave Requests",
    admin_pending_approval: "Pending Approval",
    admin_approved_this_month: "Approved This Month",
    admin_attendance_last_7_days: "Last 7 Days Attendance",
    admin_trend_weekly: "Weekly employee attendance trends",
    admin_view_details: "View Details",
    admin_dashboard_error: "Failed to load dashboard data.",

    // ── Admin Attendance Monitoring ──
    admin_attendance_title: "Attendance Monitoring",
    admin_attendance_subtitle: "Monitor employee attendance and selfie photo proof",
    admin_attendance_desc: "Monitor status and attendance logs of all employees in real-time.",
    total_staff: "Total Staff",
    export_data: "Export Data",
    filter_date: "Select Date",
    filter_dept: "All Departments",
    filter_status: "All Statuses",
    showing_label: "Showing",
    data_count: "entries",
    no_attendance_data: "No attendance data",
    no_attendance_data_desc: "No employees have clocked in on this date",
    th_employee: "Employee",
    th_department: "Department",
    th_clock_in: "Clock In",
    th_clock_out: "Clock Out",
    th_photo_proof: "Photo Proof",
    th_status: "Status",
    photo_modal_title: "Attendance Photo Proof",
    attendance_time: "Attendance Time",
    dept_position: "Department / Position",
    gps_coordinates: "GPS Coordinates",
    photo_in: "Clock-in Photo",
    photo_out: "Clock-out Photo",
    close: "Close",
    prev: "Prev",
    next: "Next",
    page_prefix: "Page",
    page_of: "of",
    attendance_load_failed: "Failed to load attendance data.",

    // ── Admin Leave Management ──
    admin_leave_title: "Leave & Request Management",
    admin_leave_subtitle: "Manage and process employee requests",
    admin_leave_desc: "Review, approve, or reject employee leave and permission requests.",
    type_sick_short: "Sick",
    type_leave_short: "Leave",
    type_permission_short: "Permission",
    no_leave_requests: "No requests found",
    no_leave_requests_desc: "No requests found for this filter",
    days_count: "days",
    rejected_prefix: "Rejected",
    processed_by: "Processed by",
    detail_btn: "Detail",
    approve_btn: "Approve",
    reject_btn: "Reject",
    reject_modal_title: "Reject Request",
    reject_modal_from: "from",
    reject_reason_label: "Rejection reason",
    optional: "(optional)",
    reject_reason_placeholder: "Write rejection reason…",
    processing: "Processing…",
    leave_detail_title: "Request Details",
    view_document: "View document →",
    attachment: "Attachment",
    approval_modal_title: "Confirm Approval",
    rejection_modal_title: "Confirm Rejection",
    leave_load_failed_admin: "Failed to load leave requests.",
    approve_failed: "Failed to approve request.",
    reject_failed: "Failed to reject request.",

    // ── Admin Employee Management ──
    admin_emp_title: "Employee Management",
    emp_registered: "registered employees",
    emp_all_registered: "All employees registered in the system",
    add_employee: "Add Employee",
    search_name_nip: "Search name or ID…",
    all_departments: "All Departments",
    emp_not_found: "Employee not found",
    emp_not_found_desc: "Try changing keywords or add a new employee",
    active: "Active",
    inactive: "Inactive",
    activate: "Activate",
    deactivate: "Deactivate",
    leave_quota_label: "Leave quota",
    edit_employee_title: "Edit Employee",
    create_employee_desc: "Fill in details to create a new employee account",
    edit_employee_desc: "Edit employee details",
    account_data: "Account Data",
    new_password_optional: "New Password (optional)",
    edit_password_placeholder: "Leave blank if unchanged",
    password_placeholder: "Min. 6 characters",
    account_status: "Account Status",
    account_status_hint: "Employee can log in if active",
    profile_data: "Profile Data",
    phone_number: "Phone Number",
    quota_hint: "Leave Quota (days/year)",
    create_employee_btn: "Create Employee",
    delete_employee_title: "Delete Employee",
    delete_employee_confirm: "will be removed from the system.",
    delete_warning: "Deleted data cannot be recovered.",
    emp_load_failed: "Failed to load employee data.",
    emp_create_failed: "Failed to create employee.",
    emp_update_failed: "Failed to update employee.",
    emp_delete_failed: "Failed to delete employee.",

    // ── Admin Report ──
    report_page_title: "Attendance Reports & Export",
    report_page_subtitle: "Summarize and download yearly, monthly, weekly, or daily attendance spreadsheets.",
    export_spreadsheet: "Export Spreadsheet (Excel / CSV)",
    exporting_spreadsheet: "Generating Spreadsheet…",
    period_yearly: "Yearly",
    period_monthly: "Monthly",
    period_weekly: "Weekly",
    period_daily: "Daily",
    period_custom: "Custom Range",
    select_year: "Select Year:",
    month_and_year: "Month & Year:",
    select_date: "Select Date:",
    from_date: "From:",
    to_date: "To:",
    this_week: "This Week",
    report_load_failed: "Failed to load attendance report.",
    export_download_failed: "Failed to download spreadsheet report.",
    search_report_placeholder: "Search employee name or NIP…",
    search_btn: "Search",
    preview_data: "Data Preview",
    show_per_page: "Show:",
    rows_unit: "rows",
    no_report_data: "No attendance data",
    no_report_data_desc: "No data matches the selected period filter.",
    total_attendance_stat: "Total Attendance",
    recorded_attendance: "Recorded attendance logs",
    of_total: "of total",
    need_action: "Needs follow-up",
    th_duration: "Duration",
    th_date: "Date",
    th_in: "In",
    th_out: "Out",
    btn_in: "In",
    btn_out: "Out",
    photo_proof_in: "Clock-In Photo Proof",
    photo_proof_out: "Clock-Out Photo Proof",
    photo_not_available: "Photo Unavailable",

    // ── Admin Settings ──
    settings_title: "System Settings",
    settings_subtitle: "Manage app configuration, attendance rules, notifications, and administrator profile",
    settings_saved: "Settings saved successfully!",
    tab_general: "General",
    tab_attendance_rules: "Attendance",
    tab_notification_settings: "Notifications",
    tab_admin_account: "Account",
    general_settings: "General Settings",
    general_settings_desc: "Basic application and company information",
    app_name: "Application Name",
    company_name: "Company Name",
    timezone: "Timezone",
    language: "Language",
    save_settings: "Save Settings",
    saving_settings: "Saving…",
    schedule_mode_title: "Work Schedule Mode",
    schedule_same_title: "Uniform Every Day",
    schedule_same_desc: "Same clock-in & clock-out time for all working days.",
    schedule_custom_title: "Different Hours Per Day (Custom)",
    schedule_custom_desc: "Set different clock-in & clock-out hours for each day (e.g. Friday special hours).",
    uniform_schedule: "Uniform Work Schedule",
    clock_in_time_label: "Work Clock-In Time",
    clock_out_time_label: "Work Clock-Out Time",
    active_work_days: "Active Working Days",
    custom_schedule_active: "Custom Work Schedule Active",
    custom_schedule_active_desc: "Each day has its own clock-in and clock-out hours.",
    preset_fri_btn: "Set Mon–Thu 08:30 & Fri 10:00",
    preset_copy_mon_btn: "Copy Monday to Tue–Thu",
    day_active_status: "Active Work Day",
    day_off_status: "Day Off",
    special_badge: "Special",
    no_attendance_required_day: "Employees are not required to attend on this day",
    rules_section_title: "Late Rules & Check-In Deadlines",
    rules_section_desc: "Grace period and cutoff limits (applies to all schedule modes).",
    late_tolerance_title: "Late Grace Period",
    late_tolerance_desc: "Grace window after start time before attendance is flagged as late.",
    cutoff_title: "Check-in Cutoff Deadline",
    cutoff_desc: "Maximum grace period before clock-in is rejected by the system.",
    custom_minutes_option: "✏️ Custom / Enter Minutes...",
    no_cutoff_option: "0 / No Cutoff (Anytime allowed)",
    unit_minutes: "Minutes",
    select_btn: "Select",
    office_radius_title: "Location & Radius",
    office_radius_label: "Check-in Radius (meters)",
    office_radius_desc: "Employees must be within this distance from the office to check in",
    notif_settings_title: "Notification Settings",
    notif_settings_desc: "Choose the notifications you want to receive",
    grp_email_attendance: "Email — Attendance",
    notif_late_emp: "Late Employees",
    notif_late_emp_desc: "Send email when an employee clocks in after deadline",
    notif_absent_emp: "Absent Employees",
    notif_absent_emp_desc: "Send daily email with list of employees who have not clocked in",
    grp_email_leave: "Email — Leave Requests",
    notif_new_leave: "New Leave Request",
    notif_new_leave_desc: "Send email when an employee submits a leave/permission request",
    notif_leave_status: "Leave Approved/Rejected",
    notif_leave_status_desc: "Send confirmation email to employee once processed",
    grp_email_reports: "Email — Automated Reports",
    notif_weekly_rep: "Weekly Report",
    notif_weekly_rep_desc: "Send attendance summary every Monday morning",
    notif_monthly_rep: "Monthly Report",
    notif_monthly_rep_desc: "Send monthly recap on the 1st of every month",
    grp_system_log: "System Logs",
    notif_admin_login: "Admin Login",
    notif_admin_login_desc: "Record every login activity to the admin panel",
    notif_data_export: "Export Data",
    notif_data_export_desc: "Record every time data is exported",
    admin_account_title: "Account Profile",
    admin_account_desc: "Manage administrator account information",
    admin_save_profile: "Save Profile",
    admin_change_pw_title: "Change Password",
    admin_current_pw: "Current Password",
    admin_new_pw: "New Password",
    admin_confirm_pw: "Confirm New Password",
    admin_btn_change_pw: "Change Password",
    admin_pw_min_error: "New password must be at least 8 characters.",
    admin_pw_match_error: "Password confirmation does not match.",
    admin_pw_curr_error: "Please enter your current password.",
  },
};

type LanguageContextValue = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
  formatDate: (date?: Date | string | null, options?: Intl.DateTimeFormatOptions) => string;
  formatTime: (date?: Date | string | null) => string;
  getGreeting: (hour?: number) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("id");

  useEffect(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("bee_app_language");
      if (saved === "en" || saved === "id") {
        setLanguageState(saved);
      }

      const handleStorage = (e: StorageEvent) => {
        if (e.key === "bee_app_language" && (e.newValue === "en" || e.newValue === "id")) {
          setLanguageState(e.newValue);
        }
      };

      const handleCustom = (e: Event) => {
        const detail = (e as CustomEvent).detail;
        if (detail === "en" || detail === "id") {
          setLanguageState(detail);
        }
      };

      window.addEventListener("storage", handleStorage);
      window.addEventListener("bee_language_changed", handleCustom);
      return () => {
        window.removeEventListener("storage", handleStorage);
        window.removeEventListener("bee_language_changed", handleCustom);
      };
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== "undefined") {
      localStorage.setItem("bee_app_language", lang);
      window.dispatchEvent(new CustomEvent("bee_language_changed", { detail: lang }));
    }
  };

  const t = (key: string, fallback?: string): string => {
    const dict = DICTIONARY[language] || DICTIONARY.id;
    return dict[key] ?? fallback ?? key;
  };

  const formatDate = (dateInput?: Date | string | null, options?: Intl.DateTimeFormatOptions): string => {
    if (!dateInput) return "-";
    let d: Date;
    if (typeof dateInput === "string") {
      const trimmed = dateInput.trim();
      if (!trimmed) return "-";
      d = new Date(trimmed.includes("T") ? trimmed : trimmed.replace(" ", "T"));
    } else {
      d = dateInput;
    }
    if (!d || isNaN(d.getTime())) return String(dateInput);
    const locale = language === "en" ? "en-US" : "id-ID";
    const defaultOptions: Intl.DateTimeFormatOptions = {
      weekday: "long",
      day: "numeric",
      month: "long",
      year: "numeric",
    };
    return new Intl.DateTimeFormat(locale, options ?? defaultOptions).format(d);
  };

  const formatTime = (dateInput?: Date | string | null): string => {
    if (!dateInput) return "--:--";
    let d: Date;
    if (typeof dateInput === "string") {
      const trimmed = dateInput.trim();
      if (!trimmed) return "--:--";
      // If only time string e.g. "08:30" or "08:30:00"
      if (/^\d{1,2}:\d{2}(:\d{2})?$/.test(trimmed)) {
        return trimmed.slice(0, 5);
      }
      d = new Date(trimmed.includes("T") ? trimmed : trimmed.replace(" ", "T"));
    } else {
      d = dateInput;
    }
    if (!d || isNaN(d.getTime())) {
      return typeof dateInput === "string" ? dateInput.slice(0, 5) : "--:--";
    }
    return new Intl.DateTimeFormat(language === "en" ? "en-US" : "id-ID", {
      hour: "2-digit",
      minute: "2-digit",
      hour12: false,
    }).format(d);
  };

  const getGreeting = (hour?: number): string => {
    const h = hour ?? new Date().getHours();
    if (language === "en") {
      if (h < 12) return "Good morning";
      if (h < 17) return "Good afternoon";
      return "Good evening";
    }
    if (h < 11) return "Selamat pagi";
    if (h < 15) return "Selamat siang";
    if (h < 18) return "Selamat sore";
    return "Selamat malam";
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, formatDate, formatTime, getGreeting }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      language: "id" as Language,
      setLanguage: () => {},
      t: (key: string, fallback?: string) => DICTIONARY.id[key] ?? fallback ?? key,
      formatDate: (d?: Date | string | null) => (d ? String(d) : "-"),
      formatTime: (d?: Date | string | null) => (d ? String(d) : "--:--"),
      getGreeting: () => "Selamat datang",
    };
  }
  return context;
}
